version: '3'

services:

  admin-ui:
    image: drill4j/admin-ui:${FRONT_VERSION}
    restart: always
    ports:
      - ${FRONT_PORT}:8080

  drill-admin:
    image: drill4j/admin:${BACK_VERSION}
    container_name: drill-admin
    environment:
      - TEST2CODE_PLUGIN_VERSION=${TEST2CODE_PLUGIN_VERSION}
      - DRILL_DEFAULT_PACKAGES=${DRILL_DEFAULT_PACKAGES}
    ports:
      - ${BACK_PORT}:8090

  mongo:
    image: mongo:3.4
    hostname: mongo
    ports:
      - '127.0.0.1:28017:27017'

  jsagent:
    image: drill4j/js-agent:${JS_AGENT_VERSION}
    container_name: jsagent
    hostname: jsagent
    ports:
      - '9404:9404'
    environment:
      APP_PORT: '9404'
      WAIT_HOSTS: mongo:27017, drill-admin:8090
      DRILL_ADMIN_PROTOCOL: 'ws'
      DRILL_ADMIN_HOST: 'drill-admin:8090'
      MONGO_HOST: 'mongo:27017'
      MONGO_DBNAME: 'js-agent'
      COVERAGE_SOURCE_APPEND_PREFIX: ${JS_AGENT_COVERAGE_SOURCE_APPEND_PREFIX}
      COVERAGE_SOURCE_OMIT_PREFIX: ${JS_AGENT_COVERAGE_SOURCE_OMIT_PREFIX}
      DEBUG: 'drill:*'
      DEBUG_COLORS: 'true'
      FORCE_COLOR: '3'
      DEBUG_LOG_LEVEL: '4'
    depends_on:
      - drill-admin

  autotest-dispatcher:
    image: drill4j/autotest-extension-dispatcher:latest
    ports:
      - '5003:5003'

  agent-files:
    image: drill4j/java-agent:${JAVA_AGENT_VERSION}
    volumes:
      - agent-files:/java-agent

volumes:
  agent-files:
