version: '3.8'

services:

  realworld-frontend-2:
    image: drill4j/real-world-angular:no-js-agent-0.9.0-build.2
    ports:
      - "${REALWORLD_FRONTEND_2_PORT}:80"
    command: nginx -g 'daemon off;'
    networks:
      - drill4j-dev-network

  realworld-api-2:
    image: drill4j/real-world-spring-api:java-and-js-coverage-0.2.0
    ports:
      - "${REALWORLD_API_2_PORT}:8080"
    environment:
      - "ACCESS_CONTROL_ALLOW_ORIGIN=http://localhost:${REALWORLD_FRONTEND_2_PORT}"
      - "JAVA_TOOL_OPTIONS=-agentpath:/data/agent/libdrill_agent.so"
      - "DRILL_API_URL=${DRILL_ADMIN_ADDRESS}"
      - "DRILL_API_KEY=${DRILL_API_KEY}"
      - "DRILL_APP_ID=${DRILL_API_AGENT_ID}"
      - "DRILL_GROUP_ID=${DRILL_GROUP_ID}"
      - "DRILL_BUILD_VERSION=0.2.0"
      - "DRILL_PACKAGE_PREFIXES=io/spring"
    volumes:
      - agent-files:/data
    entrypoint: [ "java", "-jar","/spring-boot-realworld-example-app-0.0.1-SNAPSHOT.jar" ]
    networks:
      - drill4j-dev-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  drill4j-dev-network:

volumes:
  agent-files: