version: '3'

services:

  drill-admin:
    image: ghcr.io/drill4j/admin:${BACK_VERSION}
    environment:
      - DRILL_DB_PORT=5432
      - DRILL_AGENTS_SOCKET_TIMEOUT=6000
      - DRILL_DB_HOST=${POSTGRES_HOST}
      - DRILL_DB_NAME=${POSTGRES_DB}
      - DRILL_DB_USER_NAME=${POSTGRES_USER}
      - DRILL_DB_PASSWORD=${POSTGRES_PASSWORD}
      - DRILL_DB_MAX_POOL_SIZE=${DRILL_DB_MAX_POOL_SIZE}
      - LOG_LEVEL=info
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:8090" ]
      interval: 10s
      timeout: 3s
      retries: 30
    ports:
      - 8090:8090
    networks:
      - drill4j-dev-network
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:14.1
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - drill-data-pg:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - drill4j-dev-network
    command: ["postgres", "-c", "log_statement=all", "-c", "log_min_duration_statement=0"]

  devtools-proxy:
    image: drill4j/devtools-proxy:${DEVTOOLS_PROXY_VERSION}
    ports:
      - "8093:8080"
    environment:
      DEBUG: 'drill:*'
      DEBUG_COLORS: 'true'
      FORCE_COLOR: '3'
      DEBUG_LOG_LEVEL: '4'
    extra_hosts:
      - "host.docker.internal:host-gateway"

  agent-files:
      image: drill4j/java-agent:0.8.0-38
      environment:
        - AGENT_VERSION=${JAVA_AGENT_VERSION}
      volumes:
        - agent-files:/data
      networks:
        - drill4j-dev-network

volumes:
  drill-data-pg:
  agent-files:

networks:
  drill4j-dev-network:
