version: '3'

services:

  realworld-frontend:
    # image: drill4j/real-world-angular:java-and-js-coverage-0.2.0
    image: drill4j/real-world-angular:new-0.2.0
    environment:
      DRILL_JS_AGENT_HOST: ${DRILL_JS_AGENT_HOST}
      DRILL_JS_PARSER_VERSION: ${DRILL_JS_PARSER_VERSION}
      DRILL_JS_AGENT_AGENT_ID: ${DRILL_JS_AGENT_AGENT_ID}
      DRILL_JS_AGENT_GROUP_ID: ${DRILL_GROUP_ID}
      REALWORLD_FRONTEND_BUILD_VERSION: 0.2.0
      REALWORLD_API_ADDRESS: ${REALWORLD_API_ADDRESS}
    ports:
      - "${REALWORLD_FRONTEND_PORT}:80"
    networks:
      - drill4j-dev-network

  realworld-api:
    image: drill4j/real-world-spring-api:java-and-js-coverage-0.2.0
    ports:
      - "${REALWORLD_API_PORT}:8080"
    environment:
      - "JAVA_TOOL_OPTIONS=-agentpath:/data/agent/libdrill_agent.so=drillInstallationDir=/data/agent,adminAddress=${DRILL_ADMIN_ADDRESS},agentId=${DRILL_API_AGENT_ID},groupId=${DRILL_GROUP_ID},buildVersion=0.2.0"
    depends_on:
      - db
    volumes:
      - agent-files:/data
    entrypoint: [ "java", "-jar","/spring-boot-realworld-example-app-0.0.1-SNAPSHOT.jar" ]
    networks:
      - drill4j-dev-network

  db:
    image: mysql
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=true"
    ports:
      - "3306:3306"

volumes:
  agent-files:

networks:
  drill4j-dev-network: